---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: repository
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
    - role: role_under_test
      openio_conscience_namespace: "{{ NS }}"
      openio_conscience_bind_address: "{{ ansible_default_ipv4.address }}"
      openio_conscience_pools:
        - name: rawx21
          targets:
            - where: rawx-europe
              type: rawx
              count: 2
            - where: rawx-asia
              type: rawx
              count: 1
          min_dist: 2
      openio_conscience_multiple:
        me: "{{ openio_conscience_bind_address }}:18000"
        group:
          - 172.17.0.3:18000
          - 172.17.0.4:18000
...
