---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: installed
  with_items: "{{ conscience_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"

...
